### ISSUE TITLE
Posix not available under Windows

### ISSUE THREAD

**Issue by adriansuter** [tecnickcom/tc-lib-pdf-encrypt#8]
Hi

First of all, thanks for this wonderful library.

I am currently starting a new project and wanted to switch from the old school TCPDF to the new tc-lib-pdf, as suggested in the README of TCPDF. So I changed my composer.json to load the dev-develop branch of your tc-lib-pdf package.

But as I am developing on a Windows OS, unfortunately I can not install and use your new tecnickcom/tc-lib-pdf library.

Composer is complaining:
`tecnickcom/tc-lib-pdf-encrypt 1.5.2 requires ext-posix * -> the requested PHP extension posix is missing from your system.`

The posix-extension is not available for Windows (as stated by PHP itself). Any chance to use your new package on my development machine?

**Comment by techkey** [comment]
@adriansuter 

I ran into the same issue. It seems that `tc-lib-pdf-encrypt` requires that in the json file. After looking a bit further it's used in `vendor\tecnickcom\tc-lib-pdf-encrypt\src\Type\Seed.php`:

```php
48        if (function_exists('posix_getpid')) {
49            $rnd .= posix_getpid();
50        }
```

It's inside a `if` statement, so it's unclear to me why the extension is required.

To get it installed anyway there are a few options, I took the ease one to just create a empty `php_posix.dll` for Windows. I've compiled it for PHP 7.1.6 and Windows 10 x64. Let me know if you're still struggling with it, then I upload `php_posix.dll` somewhere.

**Comment by adriansuter** [comment]
@techkey 

Great hack.

It would be good, if `posix` could be marked as optional.

**Comment by gurubakshaser** [comment]
Please tell how to resolve this issue

**Comment by gurubakshaser** [comment]
Installation request for tecnickcom/tc-lib-pdf-encrypt ^1.5.2 -> satisfiable by tecnickcom/tc-lib-pdf-encrypt[

**Comment by gurubakshaser** [comment]
- tecnickcom/tc-lib-pdf-encrypt 1.5.2 requires ext-posix * -> the requested PHP extension posix is missing from your system.

**Comment by nicolaasuni** [comment]
This should be sorted with version 1.5.3

**Comment by adriansuter** [comment]
Thanks a lot. Now I can try to change/upgrade my project.

**Comment by plyaskin** [comment]
Hi @techkey, 
Could you upload the php_posix.dll for PHP 7 nts and Windows Server 2012 r2 x64?
