### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by mrodriguezlima** [tecnickcom/tc-lib-pdf-encrypt#9]
Hi! Sorry to bother you, but I'm having some troubles with the examples.
After I run make qa_all I get:
OK (34 tests, 57 assertions)

When I run make docs I get:
ERROR: application encountered an error and can not continue. Unable to log error.
For more information turn on the debug mode using the --debug option.
Makefile:132: recipe for target 'docs' failed
make: *** [docs] Error 255

All I want to do, is with a existing pdf file, sing that file using a .pem
I can't find examples or doc

**Comment by nicolaasuni** [comment]
This library only provides primitive methods. The PDF signature function will be implemented in tc-lib-pdf.
The error you are getting is due to the broken apigen dependency that has issues with some PHP version (https://github.com/apigen/apigen/issues).
